"""create restaurants and waitlist_entries

Revision ID: 8d9b62535155
Revises:
Create Date: 2026-09-18 10:37:38.181079

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d9b62535155"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "restaurants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "waitlist_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("restaurant_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("party_size", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "WAITING",
                "CALLED",
                "SEATED",
                "CANCELLED",
                "NO_SHOW",
                name="waitliststate",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("status_token", sa.String(), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.Column("called_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_waitlist_entries_restaurant_id"),
        "waitlist_entries",
        ["restaurant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_waitlist_entries_status_token"), "waitlist_entries", ["status_token"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_waitlist_entries_status_token"), table_name="waitlist_entries")
    op.drop_index(op.f("ix_waitlist_entries_restaurant_id"), table_name="waitlist_entries")
    op.drop_table("waitlist_entries")
    op.drop_table("restaurants")
    # ### end Alembic commands ###
